task2.3
tema3210/instrumentio_work pull request #15
Opened 2024-02-14 12:16 UTC by tema3210

## Task

Refactor the code contained in [this step's crate](src/main.rs) to reduce trait bounds pollution as much as possible.

## Solution

2024-02-21 12:41 UTC, evdokimovs requested changes
Еще нужно зарелаксить трейт баунд `Default` на трейте `Aggregate`.

2024-02-21 12:41 UTC, evdokimovs commented on 2_idioms/2_3_bound_impl/README.md
> +- Why placing trait bounds on `impl` blocks is better? - bc we have no implied bounds =(
Ответы на вопросы не требуются в текстовом виде.

2024-02-23 09:15 UTC, evdokimovs requested changes
> Еще нужно зарелаксить трейт баунд Default на трейте Aggregate.

2024-02-23 10:00 UTC, evdokimovs approved these changes
LGTM, только галочку 2.4 поправьте.

2024-02-23 10:06 UTC, tema3210 commented on README.md
> +    - [x] [2.4. Abstract type in, concrete type out][Step 2.4] (1 day)
тот таск уже готов

2024-02-23 10:13 UTC, merged