Task 3.1
tema3210/instrumentio_work pull request #19
Opened 2024-02-15 15:40 UTC by tema3210

## Task

For the implementation of a small [guessing game][51] in [this step's crate](src/main.rs) provide all possible tests you're able to write.

## Solution

2024-02-23 09:37 UTC, evdokimovs requested changes
Тут Вы просто обкостылили свои BDD тесты. Они не должны так работать, поскольку сейчас это только видимость BDD тестирования, а по сути вся логика тестов у Вас реализована в `cucumber.rs`, при этом какой то гибкости и вариативности со стороны Cucumber'овских сценариев практически нет.

Также в рамках этой задачи хочется увидеть реализацию unit тестов, интеграционых тестов и prop тестов.

И не забывайте, пожалуйста, прогонять `rustfmt` и `Clippy`.

2024-02-23 09:37 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/features/game.feature
> +    Then program produces same output
Ваши тесты начнут падать, если я немного подкорректирую Ваш сценарий:

```suggestion
  Scenario: If we pass in same number
    Given a program is running
    When we pass string: 5
    And we pass string: 5
    Then program produces same output
```

Этот подкорректированный сценарий является корректным сценарием в котором тест должен корректно отрабатывать, но он ломается поскольку Вы захардкодили проверки внутри `cucumber.rs`, и по сути step `program produces same output` не делает того о чем он говорит.

2024-02-23 09:37 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/features/game.feature
> +    When we pass string: 42
Вхардкоженное число 42 для выигрыша - выглядит так себе. Как тот кто будет писать (или читать) Ваши сценарии поймет, что число 42 дает выигрыш?

Здесь лучше делать что-то вроде:

```suggestion
    When we pass a winning number
```

2024-02-23 09:37 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/cucumber.rs
> +    std::thread::sleep(Duration::from_secs(2));
`sleep`'ы в тестах - это практически всегда костыль. Хоть иногда он и не избежен, но я убежден, что в Вашем случае это можно как то сделать без слипа.

2024-02-23 09:37 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/cucumber.rs
> +    assert_eq!(line, Some("Please input your guess.\n".into()));
А если я напишу сценарий где я сначала не угадываю число, а потом угадываю? Ваш тест опять таки поломается, хотя должен был отработать нормально.

2024-02-26 09:12 UTC, evdokimovs requested changes
Также есть проблема в формулировании самих тестовых сценариев. Более подходящим подходом в таких тестах будет описывать действия пользователя, которые приводят к какому-то результату.

То есть вместо `When we pass winning number` писать что-то вроде `When Player passes winning number`. То есть писать сценарии в третьем лице.

Также поправьте форматинг, Вы постоянно отдаете на ревью не отформатированный код и `Cargo.toml`.

2024-02-26 09:12 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/cucumber.rs
> +        let the_number: usize = rand::random::<usize>() % (MAX_NUMBER_TO_GUESS + 1);
Подобный выигрышный magic number лучше просто вхардкоживать, а не пытаться генерить рандом. Иначе Вы рискуете сделать Ваши тесты нестабильными за счет вот таких вот сайд эффектов в рамках каждого теста.

Если боитесь, что что-то начнет ломаться в рамках какого то инпута, то лучше использовать prop testing.

2024-02-26 09:12 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/cucumber.rs
> +    pid: u32,
> field `pid` is never read

2024-02-26 09:12 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/cucumber.rs
> +fn we_win(world: &mut GameWorld) -> Result<(), String> {
Проблема не ушла. Вот тест, который я вполне могу захотеть написать, и ожидаю, что он будет работать:

```cucumber
  Scenario: Player guesses on second try
    Given a program is running
    When we pass string: 12
    And we pass winning number
    Then we win
```

Сам текст сценария можете поменять, если есть мысли как его сделать более понятным и гибким, но суть в том, чтобы варианты где пользователь дает какой-то инпут, а после него еще какой-то инпут - тоже работали. К примеру, мы хотим проверить, что программа не завершается после того, как пользователь неправильно угадал число.

В догонку еще можно сделать такой тест:

```cucumber
  Scenario: Player guesses after wrong input
    Given a program is running
    When we pass string: foo
    And we pass winning number
    Then we win
```

2024-02-26 09:12 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/tests/cucumber.rs
> +#[then("program produces sane output")]
У Вас тут очепятка. Такие моменты тоже нужно вычитывать перед ревью.

```suggestion
#[then("program produces same output")]
```

2024-02-26 09:12 UTC, evdokimovs commented on 3_ecosystem/3_1_testing/src/main.rs
> +        Ordering::Equal => ("You win!",true)
Тогда уж лучше завести какой-то enum или вроде того. То есть я тут могу ошибится и при рефакторинге написать что-то типа `("You win!", false)`. Ну и не особо понятно исходя из этой функции, а на что, собственно, влияет `bool`. Enum Вам поможет сделать код, который сам себя будет описывать.

2024-02-26 09:56 UTC, tema3210 commented on 3_ecosystem/3_1_testing/tests/cucumber.rs
> +#[then("program produces sane output")]
Просто плохое имя, это тест на корректность при любых условиях - его можно в then везде воткнуть, правда наверно это плохая идея.

2024-02-26 10:23 UTC, tema3210 commented on 3_ecosystem/3_1_testing/src/main.rs
> +fn get_secret_number() -> u32 {
(то была пометка для себя...)

2024-02-27 11:09 UTC, evdokimovs requested changes
1. Вычитать и подчистить код от ненужных комментов
2. Поправить форматирование
3. Поравить step `Then we win`
4. Дописать unit тесты

2024-02-27 14:23 UTC, evdokimovs approved these changes

2024-02-28 09:02 UTC, merged