Task1
tema3210/instrumentio_work pull request #20
Opened 2024-02-19 10:02 UTC by tema3210

Resolves [Step ]()

## Task

Provide your own implementation of [doubly linked list][11] data structure. It should be [thread safe][12] without a necessity to use explicit synchronization primitives (like `Arc<Mutex<T>>`) on top of it.

Prove your implementation correctness with tests. Provide both single-threaded and multi-threaded examples of usage.  

## Solution

2024-02-19 10:12 UTC, tema3210 commented
github diff is broken - 1_1 and 1_2 tasks have no difference with main (did git reset) yet github show that

2024-02-21 12:53 UTC, evdokimovs requested changes

2024-02-23 09:17 UTC, evdokimovs approved these changes

2024-02-23 09:17 UTC, evdokimovs commented on README.md
> +
Эту очепятку поправьте, в остальном LGTM.

2024-02-23 09:52 UTC, merged