Task3.6
tema3210/instrumentio_work pull request #24
Opened 2024-02-20 12:47 UTC by tema3210

Resolves [Step ]()

## Task

Write a program which deserializes the [following JSON](request.json) into a static `Request` type and prints out its serialization in a YAML and TOML formats. Consider to choose correct types for data representation.

Prove your implementation correctness with tests.

## Solution

2024-02-23 09:58 UTC, evdokimovs requested changes

2024-02-23 09:58 UTC, evdokimovs commented on 3_ecosystem/3_6_serde/src/main.rs
> +    duration: String, //should really be a Duration
Верно подметили, что это должно быть не `String`, а `Duration`. Реализуйте так, чтобы оно выпаршивало `Duration`'ы.

2024-02-23 09:58 UTC, evdokimovs commented on 3_ecosystem/3_6_serde/src/main.rs
> +    price: usize,
Здесь прям напрашивается использование newtype'ов. У Вас `price` мелькает много раз, но при этом еще пересекается по типам с id'шками. Завезите для таких штук newtype'ы.

2024-02-23 09:58 UTC, evdokimovs commented on 3_ecosystem/3_6_serde/src/main.rs
> +    r#type: String,
Есть смысл переименовать, и сказать об этом `serde` через аттрибут, чтобы не писать каждый раз при доступе к этому филду `r#...`. А то так и пальцы сломать можно, если каждый раз тянутся к `#`.

2024-02-23 09:58 UTC, evdokimovs commented on 3_ecosystem/3_6_serde/src/main.rs
> +    at: String,       // timestamp
Тоже что и с `Duration` только здесь, наверное, нужен `DateTime` какой-то.

2024-02-26 09:28 UTC, evdokimovs requested changes
Ну как бы вот:

```
---- tests::test_yaml stdout ----
thread 'tests::test_yaml' panicked at 3_ecosystem/3_6_serde/src/main.rs:82:14:
failed to parse: Error("invalid type: string \"1h\", expected struct Duration", line: 11, column: 22)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::test_toml stdout ----
thread 'tests::test_toml' panicked at 3_ecosystem/3_6_serde/src/main.rs:82:14:
failed to parse: Error("invalid type: string \"1h\", expected struct Duration", line: 11, column: 22)
```

2024-02-26 11:55 UTC, tema3210 commented
> Ну как бы вот:
> 
> ```
> ---- tests::test_yaml stdout ----
> thread 'tests::test_yaml' panicked at 3_ecosystem/3_6_serde/src/main.rs:82:14:
> failed to parse: Error("invalid type: string \"1h\", expected struct Duration", line: 11, column: 22)
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> ---- tests::test_toml stdout ----
> thread 'tests::test_toml' panicked at 3_ecosystem/3_6_serde/src/main.rs:82:14:
> failed to parse: Error("invalid type: string \"1h\", expected struct Duration", line: 11, column: 22)
> ```

Duration не работает с serde... Пришьем

2024-02-27 14:24 UTC, evdokimovs requested changes
Reread as discussed.

2024-02-29 15:01 UTC, evdokimovs approved these changes
Только `Cargo.toml` поправьте, пожалуйста.

2024-03-04 09:09 UTC, merged