Task3 7
tema3210/instrumentio_work pull request #25
Opened 2024-02-21 10:43 UTC by tema3210

Resolves [Step ]()

## Task

Implement the following functions:
1. `generate_password()`: generates random password of given length and symbols set;
2. `select_rand_val()`: retrieves random element from a given slice;
3. `new_access_token()`: generates unique cryptographically secure random value in `a-zA-Z0-9` symbols set and has exactly `64` symbols.
4. `get_file_hash()`: returns SHA-3 hash of a file specified by its path.
5. `hash_password()`: returns [Argon2] password hash for a given password.

## Solution

2024-02-27 14:25 UTC, evdokimovs requested changes
Reread as discussed.

2024-02-29 15:11 UTC, evdokimovs requested changes

2024-02-29 15:11 UTC, evdokimovs commented on 3_ecosystem/3_7_rand_crypto/src/main.rs
> +}
Можно сделать проще и красивее. В `rand` для таких вещей есть API.

2024-02-29 15:11 UTC, evdokimovs commented on 3_ecosystem/3_7_rand_crypto/src/main.rs
> +}
Для этого тоже есть более красивое решение.

2024-02-29 15:11 UTC, evdokimovs commented on 3_ecosystem/3_7_rand_crypto/src/main.rs
> +}
UUID это не про access token'ы. Вам даны условия как должен выглядеть access token:

1. `a-zA-Z0-9` - в случае с UUID у Вас там как минимум будет еще `-`, которого по условиям задачи не может быть
2. `64 symbols` - в UUID их будет 36

2024-03-04 10:11 UTC, tema3210 commented on 3_ecosystem/3_7_rand_crypto/src/main.rs
> +}
Оно есть для слайсов, масивов, и примитивов, для строки что так что этак придется руками писать (https://docs.rs/rand/latest/rand/trait.Fill.html)

2024-03-06 08:17 UTC, evdokimovs approved these changes

2024-03-06 09:34 UTC, merged